services:
  main:
    container_name: main-template
    build:
      context: .
      dockerfile: ./docker/custom/Dockerfile
      no_cache: false
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/workspace/app
