services:
  main:
    container_name: main-template-ml
    build:
      context: .
      dockerfile: ./docker/custom/Dockerfile
      no_cache: false
    # restart: unless-stopped
    restart: no
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/workspace/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
